#ifndef __CONFIG_H_
#define __CONFIG_H_

#define DEBUG_MODE
#ifdef DEBUG_MODE
#define DEBUG_LEVEL 4
#else
#define DEBUG_LEVEL 0
#endif

// #define DEPTH_MAP_VISUAL

#define SCR_WIDTH 800
#define SCR_HEIGHT 600
#define DEPTH_MAP_FBO_WIDTH SCR_WIDTH
#define DEPTH_MAP_FBO_HEIGHT SCR_HEIGHT

#define VAO_VERTEX_DATA_INDEX 0
#define VBO_VERTEX_DATA_INDEX 0

/* define GL_TEXTURE 0 ~ x meaning */
#define TEXTURE_STORED_COLOR 0
#define TEXTURE_STORED_DEPTH 1
#define SAMPLER_COLOR_TEXTURE TEXTURE_STORED_COLOR
#define SAMPLER_DEPTH_TEXTURE TEXTURE_STORED_DEPTH

#define CUBE_OBJECT_NUM 3
#define PLANE_OBJECT_NUM 1

#define VERTEX_POS_SIZE       3
#define VERTEX_NORMAL_SIZE    3
#define VERTEX_TEXTURE_SIZE   2

/* Cube */
#define CUBE_VERTEX_POS_SIZE        VERTEX_POS_SIZE
#define CUBE_VERTEX_NORMAL_SIZE     VERTEX_NORMAL_SIZE
#define CUBE_VERTEX_TEXTURE_SIZE    VERTEX_TEXTURE_SIZE

#define CUBE_VERTEX_POS_INDX        0
#define CUBE_VERTEX_NORMAL_INDX     1
#define CUBE_VERTEX_TEXTURE_INDX    2

#define CUBE_VERTEX_STRIDE          (sizeof(GLfloat) * (CUBE_VERTEX_POS_SIZE + CUBE_VERTEX_NORMAL_SIZE + CUBE_VERTEX_TEXTURE_SIZE))
#define CUBE_VERTEX_NUM(arr_size)   (arr_size / CUBE_VERTEX_STRIDE)

/* Plane */
#define PLANE_VERTEX_POS_SIZE        VERTEX_POS_SIZE
#define PLANE_VERTEX_NORMAL_SIZE     VERTEX_NORMAL_SIZE
#define PLANE_VERTEX_TEXTURE_SIZE    VERTEX_TEXTURE_SIZE

#define PLANE_VERTEX_POS_INDX        0
#define PLANE_VERTEX_NORMAL_INDX     1
#define PLANE_VERTEX_TEXTURE_INDX    2

#define PLANE_VERTEX_STRIDE          (sizeof(GLfloat) * (PLANE_VERTEX_POS_SIZE + PLANE_VERTEX_NORMAL_SIZE + PLANE_VERTEX_TEXTURE_SIZE))
#define PLANE_VERTEX_NUM(arr_size)   (arr_size / PLANE_VERTEX_STRIDE)

/* Quad */
#define QUAD_VERTEX_POS_SIZE        VERTEX_POS_SIZE
#define QUAD_VERTEX_TEXTURE_SIZE    VERTEX_TEXTURE_SIZE

#define QUAD_VERTEX_POS_INDX        0
#define QUAD_VERTEX_TEXTURE_INDX    2

#define QUAD_VERTEX_STRIDE          (sizeof(GLfloat) * (QUAD_VERTEX_POS_SIZE + QUAD_VERTEX_TEXTURE_SIZE))
#define QUAD_VERTEX_NUM(arr_size)   (arr_size / QUAD_VERTEX_STRIDE)


#endif